language: node_js
node_js:
  - "0.10"
branches:
  only:
  - master
before_script:
  - npm install -g grunt-cli
  - git config --global user.email "mateus.freira@gmail.com"
  - git config --global user.name "Travis-CI"  
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials